### ISSUE TITLE
widget measurement timestamp missing

### ISSUE THREAD

**Issue by aimilushev** [mrgames13/feinstaub-app#31] opened 2019-10-28 18:06 UTC
Previously the widget contained information of the timestamp of the measurements and refresh button. I loved that functionality and wonder why they are missing now. Unfortunatelly my sensor breaks often and looking at the widget I have no idea if the sensor is broken and when the measurements were taken. Which means that even when I have a widget I have to open the app to be sure that the data I'm looking is the latest one. This makes the widget almost meaningless for me. So please add the timestamp in the widget. And will be great if you tell me why the refresh button was removed.

**Comment by mrgames13** [comment] 2019-10-30 07:07
Hi,
we did not remove neither the timestamp not the refresh button. Please try to remove the widget from the homescreen and place it again. If that doesn't work, check if the widget has the correct size. If the height is to small, the timestamp and the refresh button disappear.
For further questions please contact us again. I leave this issue open. Please close it, if the problem is gone. Thanks!

**Comment by aimilushev** [comment] 2019-10-30 16:30
Thank you guys, I love the app and how it evolves :)

**Comment by mrgames13** [comment] 2019-11-12 12:57
We have to fit different device sizes, therefore we cannot set the widget to a fixed height. Maybe we will reopen this issue in the future.

**Closed by mrgames13** 2019-11-12 12:57 UTC
Labels: enhancement, help wanted
